title:       "Operating Systems 2021-1 (OS211)"
<<<<<<< HEAD
version:     "0023a---17-Feb-2021"
||||||| a6fafe0
version:     "0023---17-Feb-2021"
=======
version:     "0024c---18-Feb-2021"
>>>>>>> 9ea43d365bb06312704bd1c39aeae8947b31ff2b
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Cicak Bin Kadal"
address:          "Pamulang"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://cbkadal.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/cbkadal/os211/"
urlghpage:        "https://cbkadal.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

